Refactor2
shermosa/mutant-swarm pull request #2
Opened 2020-12-14 15:50 UTC by shermosa

2020-12-16 11:05 UTC, massdosage requested changes

2020-12-16 11:05 UTC, massdosage commented on src/main/java/com/hotels/mutantswarm/MutantSwarmExtension.java
> +  private HiveShellBuilder hiveShellBuilder = new HiveShellBuilder();
Move this down to method.

2021-01-04 14:55 UTC, JayGreeeen commented on src/main/java/com/hotels/mutantswarm/MutantSwarmExtension.java
> +
Niiice this method looks way better 🙌🏻  
Theres just a few empty lines that could be cleaned up

2021-01-04 17:54 UTC, JayGreeeen approved these changes

2021-01-05 16:21 UTC, JayGreeeen approved these changes

2021-01-05 16:36 UTC, massdosage approved these changes

2021-01-05 17:02 UTC, merged